export const USER_REPOSITORY = 'USER_REPOSITORY'

export const DEVICE_INFO_LOG_REPOSITORY = 'DEVICE_INFO_LOG_REPOSITORY'
export const LOGIN_LOG_REPOSITORY = 'LOGIN_LOG_REPOSITORY'
export const UPDATE_LOG_REPOSITORY = 'UPDATE_LOG_REPOSITORY'

export const PROJECT_REPOSITORY = 'PROJECT_REPOSITORY'

export const SOURCE_REPOSITORY = 'SOURCE_REPOSITORY'
